crm/crm/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('orders.urls', namespace='orders'))
]

crm/orders/urls.py
from django.urls import path

from orders import views

app_name = 'orders'


urlpatterns = [
    path('', views.HomePage.as_view(), name='index'),
    path('orders/', views.OrderListView.as_view(), name='list'),
    path('orders/create/', views.OrderCreateView.as_view(), name='create'),
    path(
        'orders/calculate/',
        views.OrderPaidListView.as_view(),
        name='calculate'
        ),
    path(
        'orders/<int:order_id>/edit/',
        views.OrderUpdateView.as_view(),
        name='edit'
    ),
    path(
        'orders/<int:order_id>/delete/',
        views.OrderDeleteView.as_view(),
        name='delete'
    ),
    path(
        'menu/<slug:category_slug>/',
        views.CategoryDetailView.as_view(),
        name='category-detail'
    )
]

crm/orders/models.py
from django.core.validators import MaxValueValidator
from django.db import models

from pytils.translit import slugify


class Table(models.Model):
    class TableNumber(models.IntegerChoices):
        FIRST = 1, '1'
        SECOND = 2, '2'
        THIRD = 3, '3'
        FOURTH = 4, '4'
        FIFTH = 5, '5'
        SIXTH = 6, '6'

    number = models.IntegerField(
        choices=TableNumber.choices,
        verbose_name='Номер стола',
        help_text='Укажите номер стола.',
        unique=True
    )

    class Meta:
        verbose_name = 'стол заказов'
        verbose_name_plural = 'Столы заказов'
        ordering = ('number',)

    def __str__(self):
        return f'{self.number} стол'


class BaseCategoryDishModel(models.Model):
    title = models.CharField(
        max_length=128,
        verbose_name='Название',
    )
    slug = models.SlugField(
        max_length=256,
        verbose_name='Идентификатор',
        help_text=('Может содержать символы латиницы, '
                   'цифры, дефис, подчёркивание.'),
        unique=True,
        blank=True
    )

    class Meta:
        abstract = True
        ordering = ('title',)

    def __str__(self):
        return self.title

    def generate_unique_slug(self):
        initial_slug = slugify(self.title)
        unique_slug = initial_slug
        n = 1
        while True:
            if not self.__class__.objects.filter(slug=unique_slug).exists():
                return unique_slug
            unique_slug = f'{initial_slug}-{n}'
            n += 1

    def save(self, *args, **kwargs):
        if not self.pk and not self.slug:
            self.slug = self.generate_unique_slug()
        return super().save(*args, **kwargs)


class Category(BaseCategoryDishModel):
    class Meta(BaseCategoryDishModel.Meta):
        verbose_name = 'категорию меню'
        verbose_name_plural = 'Категории меню'


class Dish(BaseCategoryDishModel):
    price = models.PositiveIntegerField(
        verbose_name='Цена'
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        verbose_name='Категория',
        related_name='dishes'
    )

    class Meta(BaseCategoryDishModel.Meta):
        verbose_name = 'блюдо'
        verbose_name_plural = 'Меню'


class Order(models.Model):
    class OrderStatus(models.TextChoices):
        ACCEPTED = 'accepted', 'принят'
        READY = 'ready', 'готово'
        PAID = 'paid', 'оплачено'

    table_number = models.ForeignKey(
        Table,
        on_delete=models.CASCADE,
        verbose_name='Номер стола'
    )
    items = models.ManyToManyField(
        Dish,
        through='DishOrder',
        verbose_name='Блюда'
        )

    status = models.CharField(
        max_length=16,
        choices=OrderStatus.choices,
        default=OrderStatus.ACCEPTED,
        verbose_name='Статус заказа'
    )
    created_at = models.DateTimeField(
        verbose_name='Время заказа',
        auto_now_add=True
    )

    class Meta:
        verbose_name = 'заказ'
        verbose_name_plural = 'Заказы'
        ordering = (
            '-created_at',
        )
        default_related_name = 'orders'

    def __str__(self):
        return f'Заказ {self.id}'


class DishOrder(models.Model):
    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
        verbose_name='Заказ',
        related_name='order_dishes'
    )
    dish = models.ForeignKey(
        Dish,
        on_delete=models.CASCADE,
        verbose_name='Блюдо',
    )
    amount = models.PositiveSmallIntegerField(
        verbose_name='Кол-во',
        validators=[MaxValueValidator(32767)]
    )

    class Meta:
        verbose_name = 'блюдо'
        verbose_name_plural = 'блюда'
        ordering = ('order',)

    def __str__(self):
        return self.dish.title

crm/users/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

crm/orders/forms.py
from django import forms


from orders.models import DishOrder, Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = (
            'id',
            'table_number',
            'status'
        )


class DishForm(forms.ModelForm):
    class Meta:
        model = DishOrder
        fields = (
            'dish',
            'amount'
        )


DishFormSet = forms.inlineformset_factory(
    Order,
    DishOrder,
    form=DishForm,
    extra=1,
    can_delete=False
)

crm/orders/views.py
from django.db import transaction
from django.db.models import F, Sum
from django.views.generic import (CreateView, DeleteView, DetailView,
                                  TemplateView, UpdateView)

from django_filters.views import FilterView


from orders.filters import OrderDateRangeFilter, OrderFilter
from orders.forms import DishFormSet, OrderForm
from orders.mixins import OrderMixin
from orders.models import Category, Order


class HomePage(TemplateView):
    template_name = 'orders/index.html'


class OrderListView(FilterView):
    model = Order
    template_name = 'orders/order_list.html'
    filterset_class = OrderFilter

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.annotate(
            total_price=Sum(
                F('order_dishes__dish__price') * F('order_dishes__amount')
            )
        ).select_related('table_number').order_by('-created_at')


class OrderPaidListView(OrderListView):
    filterset_class = OrderDateRangeFilter

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(status='paid')

    @staticmethod
    def get_total(queryset):
        return queryset.aggregate(Sum('total_price'))

    def get_context_data(self, **kwagrs):
        context = super(OrderPaidListView, self).get_context_data(**kwagrs)
        object_list = context['object_list']
        context['total'] = self.get_total(object_list)
        return context


class OrderCreateView(OrderMixin, CreateView):
    form_class = OrderForm

    def get_context_data(self, **kwargs):
        context = super(OrderCreateView, self).get_context_data(**kwargs)
        context['dish_formset'] = DishFormSet(self.request.POST or None)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        dish_formset = context['dish_formset']
        with transaction.atomic():
            if form.is_valid() and dish_formset.is_valid():
                self.object = form.save()
                dish_formset.instance = self.object
                dish_formset.save()
        return super(CreateView, self).form_valid(form)


class OrderUpdateView(OrderMixin, UpdateView):
    form_class = OrderForm
    pk_url_kwarg = 'order_id'

    def get_context_data(self, **kwargs):
        context = super(OrderUpdateView, self).get_context_data(**kwargs)
        context['dish_formset'] = DishFormSet(self.request.POST or None,
                                              instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        dish_formset = context['dish_formset']
        with transaction.atomic():
            if form.is_valid() and dish_formset.is_valid():
                form.save()
                dish_formset.save()
        return super(OrderUpdateView, self).form_valid(form)


class OrderDeleteView(OrderMixin, DeleteView):
    pk_url_kwarg = 'order_id'


class CategoryDetailView(DetailView):
    model = Category
    slug_url_kwarg = 'category_slug'

crm/users/views.py
from django.shortcuts import render

# Create your views here.

crm/templates/base.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <style type="text/css">
      body { background: AliceBlue !important; }
    </style>
    <title>
      {% block title %}{% endblock %}
    </title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <script src="https://code.jquery.com/jquery-3.7.1.slim.js" integrity="sha256-UgvvN8vBkgO0luPSUl2s8TIlOSYRoGFAX4jlCIm9Adc=" crossorigin="anonymous"></script>

  </head>
  <body>
    {% include 'includes/header.html' %}
    <main>
      {% block content %}{% endblock %}
    </main>
    {% block bottom_scripts %}{% endblock %}
  </body>
</html>

crm/templates/includes/header.html
{% load static %}
{% load django_bootstrap5 %}
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'orders:index' %}">
      <img src=" {% static 'img/logo.png' %}" alt="" width="30" height="30" class="d-inline-block align-text-top">
      Вкусная Гавань
      </a>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        {% with request.resolver_match.view_name as view_name %}
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link {% if view_name == 'orders:create' %} active {% endif %}" href="{% url 'orders:create' %}">
                Создать заказ
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if view_name == 'orders:list' %} active {% endif %}" aria-current="page" href="{% url 'orders:list' %}">
                Заказы
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if view_name == 'orders:calculate' %} active {% endif %}" aria-current="page" href="{% url 'orders:calculate' %}">
                Выручка
              </a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle {% if view_name == 'something' %} active {% endif %}" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Меню
              </a>
              <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                {% for category in categories %}
                  <li><a class="dropdown-item" href="{% url 'orders:category-detail' category.slug %}">{{ category.title }}</a></li>
                {% endfor %}
              </ul>
            </li>
          </ul>
        {% endwith %}
      </div>
    </div>
  </nav>
</header>

crm/templates/includes/order_card.html
{% load django_bootstrap5 %}
<div class="col mb-3">
  <div class="card border-dark h-100" style="width: 18rem;">
    <div class="card-header d-flex justify-content-between">
      {{ order.created_at|date:"d N H:i" }}
      <a href="{% url 'orders:edit' order.id %}" class="btn btn-outline-dark btn-sm">
        Изменить
      </a>
      <a href="{% url 'orders:delete' order.id %}" class="btn btn-outline-danger btn-sm">
        Удалить
      </a>
    </div>
    <div class="card-body">
      <div class="d-flex justify-content-between">
        <h5 class="card-title">Заказ {{ order.id }}</h5>
        <h6 class="card-title">{{ order.table_number }}</h6>
      </div>
      {% if order.status == 'accepted' %}
        <h6 class="card-subtitle text-warning">Принят</h6>
      {% elif order.status == 'ready' %}
        <h6 class="card-subtitle text-primary">Готов</h6>
      {% elif order.status == 'paid' %}
        <h6 class="card-subtitle text-success">Оплачен</h6>
      {% else %}
        <h6 class="card-subtitle text-secondary">На уточнении</h6>
      {% endif %}
      <br>
      {% for obj in order.order_dishes.all %}
        <span class="card-text">{{ obj.dish.title }} x {{ obj.amount }}</span><br>
      {% endfor %}
    </div>
    <div class="card-footer">
      {% if order.status == 'paid' %} Оплачено: {% else %} К оплате: {% endif %} {{ order.total_price }} р.
    </div>
  </div>
</div>

crm/templates/orders/category_detail.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block title %}
  {{ category.title }}
{% endblock %}
{% block content %}
  <div class="row row-cols-auto p-1 m-1">
    {% for dish in category.dishes.all %}
      <div class="col mb-3">
        <div class="card" style="width: 18rem;">
          <img src="{% static 'img/logo.png' %}" class="card-img-top" alt="Фото">
          <div class="card-body">
            <h5 class="card-title text-center">{{ dish.title }}</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <a href="#" class="btn btn-secondary">Подробнее</a>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

crm/templates/orders/index.html
{% extends "base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% block title %}
  Вкусная Гавань
{% endblock title%}
{% block content %}
  <div class="container-fluid">
    <div class="container pt-4 text-center">
      <h1>Ресторанчик</br> <i><b>Вкусная Гавань</b></i></h1>
    </div>
    <div class="row justify-content-between pt-5">
      <div class="col-5">
        <img src="{% static 'img/fasad.png' %}" height="680px" align="center" alt="" >
      </div>
      <div class="col-5">
        <img src="{% static 'img/inside.png' %}" align="center" alt="" >
      </div>
    </div>
    <div class="row pt-5">
      <div class="col-6 text-center">
        <h4>Контакты</h4>
        <p><i>г. Красноярск, ул. Никитина 18</i></p>
        <p><i>тел. +7(999)999-99-99</i></p>
        <p><i>E-mail: vselipoeli@example.com</i></p>
      </div>
      <div class="col-6 text-center">
        <h4>Юридическая информация</h4>
        <p><i>ИНН/КПП: 2465358995/246501001</i></p>
        <p><i>ОГРН: 1242400000260</i></p>
        <p><i>Юридический адрес: 660022, Красноярский край, г. Красноярск,<br>
          ул. Никитина, д. 18, помещ. 3 </i>
        </p>
      </div>
    </div>
  </div>
{% endblock content%}

crm/templates/orders/order_form.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block title %}
  {% if 'edit' in request.path %}
    Редактирование заказа
  {% elif 'delete' in request.path %}
    Удаление заказа
  {% else %}
    Добавление заказа
  {% endif %}
{% endblock title %}
{% block content %}
  <div class="container d-flex justify-content-center">
    <div class="card col-4 m-2">
      <div class="card-header">
        {% if 'edit' in request.path %}
          Редактирование заказа
        {% elif 'delete' in request.path %}
          Удаление заказа
        {% else %}
          Добавление заказа
        {% endif %}
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {% if not 'delete' in request.path %}
            {% bootstrap_form form %}
            {{ dish_formset.management_form }}
            {{ dish_formset.non_form_errors }}
            {% for form in dish_formset %}
              <div class="inline {{ dish_formset.prefix }} mb-2">
                {% bootstrap_form form %}
              </div>
            {% endfor %}
          {% else %}
            <article>
              <p>Удалить заказ {{ order.id }} от {{ order.created_at }}?</p>
            </article>
          {% endif %}
          <div class="d-flex justify-content-center mt-2">
            {% bootstrap_button button_type="submit" content="Отправить" %}
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}
{% block bottom_scripts %}
  <script src="{% static 'js/jquery.formset.js' %}"></script>
  <script type="text/javascript">
      $(function() {
          $(".inline.{{ dish_formset.prefix }}").formset({
              prefix: "{{ dish_formset.prefix }}",
              addCssClass: "btn btn-sm btn-outline-primary inline-form-add",
              deleteCssClass: "btn btn-sm btn-outline-danger",
              addText: 'Добавить',
              deleteText: 'Удалить',
              formCssClass: 'inline-form'
          })
      });
  </script>
{% endblock %}

crm/templates/orders/order_form_old.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block title %}
  {% if 'edit' in request.path %}
    Редактирование заказа
  {% elif 'delete' in request.path %}
    Удаление заказа
  {% else %}
    Добавление заказа
  {% endif %}
{% endblock title %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card col-3 m-2">
      <div class="card-header">
        {% if 'edit' in request.path %}
          Редактирование заказа
        {% elif 'delete' in request.path %}
          Удаление заказа
        {% else %}
          Добавление заказа
        {% endif %}
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {% if not 'delete' in request.path %}
            {% bootstrap_form form %}
          {% else %}
            <article>
              <p>Удалить заказ {{ order.id }} от {{ order.created_at }}?</p>
            </article>
          {% endif %}
          {% bootstrap_button button_type="submit" content="Отправить" %}
        </form>
      </div>
    </div>
  </div>
{% endblock content %}
{% block bottom_scripts %}
  <script src="{% static 'js/jquery.formset.js' %}"></script>
  <script type="text/javascript">
      $(function() {
          $(".inline.{{ dish_formset.prefix }}").formset({
              prefix: "{{ dish_formset.prefix }}", // The form prefix for your django formset
              addText: 'Добавить', // Text for the add link
              deleteText: 'Удалить', // Text for the delete link
          })
      });
  </script>
{% endblock %}

crm/templates/orders/order_list.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block title %}
  {% if 'calculate' in request.path %}
    Выручка
  {% else %}
    Заказы
  {% endif %}
{% endblock title %}

{% block content %}
  {% with request.resolver_match.view_name as view_name %}
    <div class="row ms-auto me-auto">
      <form method="get">
        <div class="d-flex align-items-center">
          {% if view_name == 'orders:calculate' %}
            {{ filter.form }}
          {% else %}
            {% bootstrap_form filter.form %}
          {% endif %}
          <div class="p-2">
            {% bootstrap_button "Применить" button_type="submit" button_class="btn-outline-success btn-sm" %}
          </div>
          <div class="p-2">
            {% if view_name == 'orders:calculate' %}
              {% bootstrap_button "Сбросить" button_type="link" button_class="btn-outline-danger btn-sm" href="/orders/calculate" %}
            {% else %}
              {% bootstrap_button "Сбросить" button_type="link" button_class="btn-outline-danger btn-sm" href="/orders" %}
            {% endif %}
          </div>
        </div>
      </form>
      <hr>
    </div>
    <div class="row row-cols-auto me-auto ms-auto">
      {% for order in order_list %}
        {% include 'includes/order_card.html' %}
      {% empty %}
        <h2>Заказов нет</h2>
      {% endfor %}
    </div>
    {% if view_name == 'orders:calculate' %}
      {% if total.total_price__sum %}<hr><h2>Итого: {{ total.total_price__sum }} р.</h2>{% endif %}
    {% endif %}
  {% endwith %}
{% endblock content %}